#!/usr/bin/env python3
# ==============================================================================
# client.py - GA Workload Identity Federation with X.509 Certificates Client
# ==============================================================================
# This script demonstrates Google Cloud's General Availability (GA) X.509
# Certificate Federation feature:
# 1. Loads credential configuration generated by gcloud create-cred-config.
# 2. Uses google-auth SDK to natively perform mutual TLS (mTLS) authentication
#    directly against Google Security Token Service (STS) using client.pem/key.
# 3. Automatically exchanges the X.509 certificate for a federated token and
#    impersonates the target Service Account (wif-target-sa).
# 4. Accesses a test Google Cloud Storage (GCS) bucket using the verified token.
# ==============================================================================

import os
import sys
import json
import logging
import argparse
import requests

# Configure logging per Mandatory Secure Web Skills (clear diagnostic logging)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [WIF-X509-Client] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger("WIF-X509-Client")


def parse_arguments():
    parser = argparse.ArgumentParser(description="GCP GA Workload Identity Federation X.509 Demo Client")
    parser.add_argument("--config", default="client_config.json", help="Path to client_config.json generated by deploy_gcp.sh")
    parser.add_argument("--bucket", help="Override test Cloud Storage Bucket Name")
    parser.add_argument("--local-dev", action="store_true", help="Perform offline cryptographic verification of local certificates")
    return parser.parse_args()


def verify_local_certificates(cert_path: str, root_path: str):
    """Performs offline cryptographic verification of client.pem against rootCA.pem."""
    logger.info("=" * 78)
    logger.info("OFFLINE LOCAL DEV MODE: Verifying local X.509 certificate chain...")
    logger.info("=" * 78)
    try:
        from cryptography import x509
        from cryptography.hazmat.backends import default_backend
        from cryptography.hazmat.primitives.asymmetric import padding

        with open(cert_path, "rb") as f:
            client_cert = x509.load_pem_x509_certificate(f.read(), default_backend())
        with open(root_path, "rb") as f:
            root_cert = x509.load_pem_x509_certificate(f.read(), default_backend())

        # Verify signature
        root_pubkey = root_cert.public_key()
        root_pubkey.verify(
            client_cert.signature,
            client_cert.tbs_certificate_bytes,
            padding.PKCS1v15(),
            client_cert.signature_hash_algorithm
        )
        subject_cn = client_cert.subject.get_attributes_for_oid(x509.NameOID.COMMON_NAME)[0].value
        issuer_cn = client_cert.issuer.get_attributes_for_oid(x509.NameOID.COMMON_NAME)[0].value

        logger.info("[SUCCESS] Offline cryptographic verification PASSED!")
        logger.info(f"  -> Subject Common Name (CN): {subject_cn}")
        logger.info(f"  -> Issuer Common Name (CN):  {issuer_cn}")
        logger.info(f"  -> Validity:                 {client_cert.not_valid_before_utc} to {client_cert.not_valid_after_utc}")
        logger.info("=" * 78)
        logger.info("To test live Google Cloud STS mTLS federation and GCS access, run:")
        logger.info("  ./deploy_gcp.sh <PROJECT_ID> && python3 client.py --config client_config.json")
        logger.info("=" * 78)
    except Exception as e:
        logger.error(f"[FAILED] Offline cryptographic verification failed: {e}")
        sys.exit(1)


def main():
    args = parse_arguments()
    workspace_dir = os.path.abspath(os.path.dirname(__file__))

    client_cert_path = os.path.join(workspace_dir, "client.pem")
    client_key_path = os.path.join(workspace_dir, "client.key")
    root_ca_path = os.path.join(workspace_dir, "rootCA.pem")

    for filepath, name in [(client_cert_path, "Client Cert"), (client_key_path, "Client Key")]:
        if not os.path.exists(filepath):
            logger.error(f"{name} file not found at: {filepath}")
            logger.error("Please run ./setup_cas.sh (or ./setup_pki.sh) first to generate certificates.")
            sys.exit(1)

    if args.local_dev:
        if not os.path.exists(root_ca_path):
            logger.error(f"Root CA file not found at: {root_ca_path}")
            sys.exit(1)
        verify_local_certificates(client_cert_path, root_ca_path)
        return

    config_path = os.path.join(workspace_dir, args.config)
    if not os.path.exists(config_path):
        logger.error(f"Configuration file '{args.config}' not found at: {config_path}")
        logger.error("Please run ./deploy_gcp.sh first to configure GA WIF X.509 federation.")
        sys.exit(1)

    logger.info("=" * 78)
    logger.info("Starting GA Workload Identity Federation X.509 Certificate Client Flow")
    logger.info("=" * 78)
    logger.info(f"  Credential Config: {config_path}")
    logger.info(f"  Client Cert:       {client_cert_path}")
    logger.info("=" * 78)

    # ==========================================================================
    # Step 1: Load Credentials & Perform mTLS X.509 Token Exchange via Google SDK
    # ==========================================================================
    logger.info("[Step 1/2] Loading WIF X.509 credentials & performing mTLS STS exchange...")
    try:
        from google.auth import load_credentials_from_file
        from google.auth.transport.requests import Request as GCPRequest

        # Ensure default certificate config is found if use_default_certificate_config is true
        possible_cert_configs = [
            os.path.expanduser("~/.config/gcloud/certificate_config.json"),
        ]
        for cfg_path in possible_cert_configs:
            if os.path.exists(cfg_path):
                os.environ["GOOGLE_API_CERTIFICATE_CONFIG"] = cfg_path
                logger.info(f"  Using certificate config: {cfg_path}")
                break

        credentials, project = load_credentials_from_file(
            config_path,
            scopes=["https://www.googleapis.com/auth/cloud-platform"]
        )
        auth_req = GCPRequest()
        
        # Trigger native mTLS token exchange against Google STS & impersonation
        credentials.refresh(auth_req)
    except Exception as e:
        import traceback
        traceback.print_exc()
        logger.error(f"[Step 1 FAILED] Could not authenticate via GA WIF X.509 federation: {e}")
        logger.error("Troubleshooting: Verify that trust_store.yaml in your X.509 WIF provider matches rootCA.pem.")
        sys.exit(1)

    logger.info("[Step 1 SUCCESS] Successfully authenticated via X.509 mTLS to Google STS!")
    logger.info(f"  -> Impersonated Target SA: {getattr(credentials, 'service_account_email', 'Target SA')}")
    logger.info(f"  -> Access Token Prefix:    {credentials.token[:15]}...")

    # ==========================================================================
    # Step 2: Access Cloud Storage using the Impersonated Token
    # ==========================================================================
    with open(config_path, "r") as f:
        config_data = json.load(f)
    
    # Infer bucket name from project ID or argument
    sa_email = getattr(credentials, 'service_account_email', '') or config_data.get("service_account_impersonation_url", "")
    if "@" in sa_email and ".iam.gserviceaccount.com" in sa_email:
        project_id = sa_email.split("@")[1].split(".iam.gserviceaccount.com")[0]
    else:
        project_id = config_data.get("audience", "").split("/projects/")[1].split("/")[0] if "/projects/" in config_data.get("audience", "") else ""
    bucket_name = args.bucket or f"demo-wif-mtls-{project_id}" if project_id else ""

    if not bucket_name:
        logger.error("[Step 2 FAILED] Could not determine target GCS bucket name. Use --bucket to specify.")
        sys.exit(1)

    gcs_url = f"https://storage.googleapis.com/storage/v1/b/{bucket_name}/o"
    logger.info(f"[Step 2/2] Verifying authorization by listing objects in GCS bucket: gs://{bucket_name}...")

    gcs_headers = {
        "Authorization": f"Bearer {credentials.token}",
        "Accept": "application/json"
    }

    try:
        gcs_resp = requests.get(gcs_url, headers=gcs_headers, timeout=15)
    except Exception as e:
        logger.error(f"[Step 2 FAILED] Could not call GCS API: {e}")
        sys.exit(1)

    if gcs_resp.status_code != 200:
        logger.error(f"[Step 2 FAILED] GCS API returned HTTP {gcs_resp.status_code}: {gcs_resp.text}")
        logger.error(f"Troubleshooting: Ensure roles/storage.objectViewer is granted on bucket gs://{bucket_name}.")
        sys.exit(1)

    gcs_data = gcs_resp.json()
    items = gcs_data.get("items", [])
    logger.info("[Step 2 SUCCESS] Successfully listed objects in Cloud Storage bucket!")
    logger.info("=" * 78)
    logger.info(f"  Bucket Name: gs://{bucket_name}")
    logger.info(f"  Total Objects Found: {len(items)}")
    for idx, item in enumerate(items, 1):
        logger.info(f"    [{idx}] {item.get('name')} (Size: {item.get('size')} bytes, Updated: {item.get('updated')})")
    logger.info("=" * 78)
    logger.info("GA WORKLOAD IDENTITY FEDERATION X.509 DEMO EXECUTED WITH 100% SUCCESS!")
    logger.info("=" * 78)


if __name__ == "__main__":
    main()
