#!/usr/bin/env python3
# ==============================================================================
# client.py - Standalone Client Test Script for WIF mTLS X.509 Authentication
# ==============================================================================
# This script executes the complete end-to-end WIF authentication flow:
# 1. Performs mTLS handshake / presents X.509 client certificate to the Cloud Run broker.
# 2. Retrieves a short-lived OIDC ID token signed by Google Cloud IAM signJwt.
# 3. Exchanges the OIDC ID token at Google Security Token Service (STS) for a
#    GCP Federated Access Token.
# 4. Impersonates a target Google Cloud Service Account via IAM Credentials API.
# 5. Accesses a test Google Cloud Storage (GCS) bucket using the impersonated token.
# ==============================================================================

import os
import sys
import json
import logging
import argparse
import urllib.parse
import base64
import subprocess
import requests

# Configure logging per Mandatory Secure Web Skills (clear diagnostic logging)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [WIF-Client] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger("WIF-mTLS-Client")


def parse_arguments():
    parser = argparse.ArgumentParser(description="GCP WIF mTLS Certificate Authentication Demo Client")
    parser.add_argument("--config", default="client_config.json", help="Path to client_config.json generated by deploy_gcp.sh")
    parser.add_argument("--broker-url", help="Override Cloud Run Broker URL")
    parser.add_argument("--project-number", help="Override GCP Project Number")
    parser.add_argument("--pool-id", default="demo-cert-pool", help="Workload Identity Pool ID")
    parser.add_argument("--provider-id", default="demo-cert-provider", help="Workload Identity Provider ID")
    parser.add_argument("--target-sa", help="Target Service Account Email to impersonate")
    parser.add_argument("--bucket", help="Test Cloud Storage Bucket Name")
    parser.add_argument("--local-dev", action="store_true", help="Run against local development broker (http://127.0.0.1:8080)")
    return parser.parse_args()


def decode_jwt_payload_for_logging(jwt_str: str) -> dict:
    """Decodes JWT payload without cryptographic verification for diagnostic logging."""
    try:
        parts = jwt_str.split(".")
        if len(parts) >= 2:
            payload_b64 = parts[1]
            # Add padding if needed
            padding_needed = 4 - (len(payload_b64) % 4)
            if padding_needed and padding_needed < 4:
                payload_b64 += "=" * padding_needed
            return json.loads(base64.urlsafe_b64decode(payload_b64).decode("utf-8"))
    except Exception as e:
        logger.debug(f"Could not decode JWT payload for logging: {e}")
    return {}


def get_cloud_run_invoker_token(url: str) -> str:
    """
    Obtains a GCP IAM Identity Token to authenticate against Cloud Run edge IAM proxy
    when Organization Policy (Domain Restricted Sharing) forbids public unauthenticated
    access (allUsers). Prioritizes gcloud CLI first for workstation ADC environments.
    """
    # 1. Try gcloud CLI first (most reliable on developer workstations and gLinux)
    try:
        token_bytes = subprocess.check_output(
            ["gcloud", "auth", "print-identity-token"],
            stderr=subprocess.DEVNULL
        )
        token = token_bytes.decode("utf-8").strip()
        if token:
            logger.info("Obtained Cloud Run invoker ID token via gcloud CLI.")
            return token
    except Exception as e:
        logger.debug(f"Could not fetch ID token via gcloud CLI: {e}")

    # 2. Fallback to SDK (for service accounts / GCE metadata server in production)
    try:
        from google.auth.transport.requests import Request as GCPRequest
        from google.oauth2 import id_token as gcp_id_token
        auth_req = GCPRequest()
        token = gcp_id_token.fetch_id_token(auth_req, url)
        if token:
            logger.info("Obtained Cloud Run invoker ID token via SDK.")
            return token
    except Exception as e:
        logger.debug(f"Could not fetch ID token via SDK: {e}")

    logger.warning("Could not obtain GCP IAM Identity Token for Cloud Run invocation. Proceeding unauthenticated.")
    return ""


def main():
    args = parse_arguments()
    workspace_dir = os.path.abspath(os.path.dirname(__file__))

    # Absolute paths to PKI certificate files
    client_cert_path = os.path.join(workspace_dir, "client.pem")
    client_key_path = os.path.join(workspace_dir, "client.key")
    root_ca_path = os.path.join(workspace_dir, "rootCA.pem")

    # Verify certificate files exist
    for filepath, name in [(client_cert_path, "Client Cert"), (client_key_path, "Client Key"), (root_ca_path, "Root CA")]:
        if not os.path.exists(filepath):
            logger.error(f"{name} file not found at: {filepath}")
            logger.error("Please run ./setup_pki.sh first to generate mock PKI certificates.")
            sys.exit(1)

    # Load configuration from file or arguments
    config = {}
    config_path = os.path.join(workspace_dir, args.config)
    if os.path.exists(config_path):
        logger.info(f"Loading WIF configuration from: {config_path}")
        with open(config_path, "r") as f:
            config = json.load(f)
    elif not args.local_dev:
        logger.warning(f"Configuration file '{args.config}' not found.")
        logger.warning("If testing against live GCP, ensure ./deploy_gcp.sh has been run.")

    if args.local_dev:
        broker_url = args.broker_url or "http://127.0.0.1:8080"
    else:
        broker_url = args.broker_url or config.get("broker_url", "")

    project_number = args.project_number or config.get("project_number", "")
    pool_id = args.pool_id or config.get("pool_id", "demo-cert-pool")
    provider_id = args.provider_id or config.get("provider_id", "demo-cert-provider")
    target_sa = args.target_sa or config.get("target_sa", "")
    bucket_name = args.bucket or config.get("bucket_name", "")

    if not broker_url:
        logger.error("No Broker URL specified! Use --broker-url, --local-dev, or provide a valid client_config.json.")
        sys.exit(1)

    logger.info("=" * 78)
    logger.info("Starting WIF mTLS X.509 Certificate Authentication Client Flow")
    logger.info("=" * 78)
    logger.info(f"  Broker URL:     {broker_url}")
    logger.info(f"  Client Cert:    {client_cert_path}")
    logger.info(f"  GCP Project #:  {project_number or '(Not configured - Local Dev Only)'}")
    logger.info(f"  Target SA:      {target_sa or '(Not configured - Local Dev Only)'}")
    logger.info(f"  Test Bucket:    {bucket_name or '(Not configured - Local Dev Only)'}")
    logger.info("=" * 78)

    # ==========================================================================
    # Step 1: Perform mTLS Handshake & Retrieve OIDC ID Token from Broker
    # ==========================================================================
    logger.info("[Step 1/4] Authenticating to Cloud Run Broker via X.509 Client Certificate...")
    
    # Read client PEM string to pass in X-Client-Cert header (for standard Cloud Run PoC testing
    # where outer TLS is terminated by Cloud Run ingress without mTLS trust config)
    with open(client_cert_path, "r") as f:
        client_cert_pem_str = f.read()

    headers = {
        "X-Client-Cert": urllib.parse.quote(client_cert_pem_str),
        "Content-Type": "application/json",
        "Accept": "application/json"
    }

    # If calling live Cloud Run that requires IAM invocation authentication due to
    # Domain Restricted Sharing Organization Policy, attach an IAM Identity Token.
    if not args.local_dev and broker_url.startswith("https://"):
        invoker_token = get_cloud_run_invoker_token(broker_url)
        if invoker_token:
            headers["Authorization"] = f"Bearer {invoker_token}"

    token_url = f"{broker_url.rstrip('/')}/token"
    try:
        # Determine SSL verification: use rootCA.pem if local/custom SSL, otherwise system CA bundle
        verify_ssl = root_ca_path if (broker_url.startswith("https://localhost") or broker_url.startswith("https://127.0.0.1")) else True
        if broker_url.startswith("http://"):
            verify_ssl = False

        resp = requests.post(
            token_url,
            cert=(client_cert_path, client_key_path),
            verify=verify_ssl,
            headers=headers,
            timeout=15
        )
    except Exception as e:
        logger.error(f"Failed to connect to token broker at {token_url}: {e}")
        sys.exit(1)

    if resp.status_code != 200:
        logger.error(f"[Step 1 FAILED] Broker returned HTTP {resp.status_code}: {resp.text}")
        logger.error("Troubleshooting: If HTTP 403, verify that your gcloud session has roles/run.invoker on mtls-token-broker.")
        sys.exit(1)

    token_data = resp.json()
    oidc_id_token = token_data.get("id_token")
    if not oidc_id_token:
        logger.error("[Step 1 FAILED] Broker response did not contain an 'id_token'!")
        sys.exit(1)

    decoded_claims = decode_jwt_payload_for_logging(oidc_id_token)
    logger.info("[Step 1 SUCCESS] Obtained signed OIDC ID Token from Broker!")
    logger.info(f"  -> Token Issuer (iss):   {decoded_claims.get('iss')}")
    logger.info(f"  -> Token Subject (sub):  {decoded_claims.get('sub')}")
    logger.info(f"  -> Token Audience (aud): {decoded_claims.get('aud')}")
    logger.info(f"  -> Token Expiry (exp):   {decoded_claims.get('exp')}")

    # If in local_dev mode OR real GCP parameters are not configured, stop cleanly after Step 1
    if args.local_dev or not project_number or not target_sa or not bucket_name:
        logger.info("=" * 78)
        logger.info("LOCAL DEV MODE / PARTIAL CONFIGURATION DETECTED:")
        logger.info("Step 1 (mTLS X.509 Authentication & OIDC ID Token issuance) succeeded!")
        logger.info("The local broker successfully verified client.pem against rootCA.pem,")
        logger.info("extracted Subject CN='client-01', and issued a valid OIDC ID Token.")
        logger.info("To test live GCP WIF Token Exchange and GCS authorization, deploy to")
        logger.info("Cloud Run using ./deploy_gcp.sh and run: python3 client.py")
        logger.info("=" * 78)
        return

    # ==========================================================================
    # Step 2: Exchange OIDC Token for GCP Federated Token via Google STS API
    # ==========================================================================
    sts_url = "https://sts.googleapis.com/v1/token"
    audience = f"//iam.googleapis.com/projects/{project_number}/locations/global/workloadIdentityPools/{pool_id}/providers/{provider_id}"
    
    logger.info(f"[Step 2/4] Exchanging OIDC ID token for GCP Federated Token via Google STS...")
    logger.info(f"  -> STS Endpoint: {sts_url}")
    logger.info(f"  -> WIF Audience: {audience}")

    sts_payload = {
        "grant_type": "urn:ietf:params:oauth:grant-type:token-exchange",
        "audience": audience,
        "scope": "https://www.googleapis.com/auth/cloud-platform",
        "requested_token_type": "urn:ietf:params:oauth:token-type:access_token",
        "subject_token_type": "urn:ietf:params:oauth:token-type:id_token",
        "subject_token": oidc_id_token
    }

    try:
        sts_resp = requests.post(sts_url, data=sts_payload, timeout=15)
    except Exception as e:
        logger.error(f"[Step 2 FAILED] Could not call Google STS API: {e}")
        sys.exit(1)

    if sts_resp.status_code != 200:
        logger.error(f"[Step 2 FAILED] Google STS API returned HTTP {sts_resp.status_code}: {sts_resp.text}")
        logger.error("Troubleshooting: Verify that ISSUER_URI in WIF Provider matches Broker URL and JWKS endpoint is accessible.")
        sys.exit(1)

    sts_data = sts_resp.json()
    federated_token = sts_data.get("access_token")
    logger.info("[Step 2 SUCCESS] Obtained GCP Federated Access Token from Google STS!")
    logger.info(f"  -> Federated Token Prefix: {federated_token[:15]}... (Expires in: {sts_data.get('expires_in')}s)")

    # ==========================================================================
    # Step 3: Impersonate Target Service Account via IAM Credentials API
    # ==========================================================================
    iam_url = f"https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/{target_sa}:generateAccessToken"
    logger.info(f"[Step 3/4] Impersonating Target Service Account: {target_sa}...")

    iam_headers = {
        "Authorization": f"Bearer {federated_token}",
        "Content-Type": "application/json"
    }
    iam_payload = {
        "scope": ["https://www.googleapis.com/auth/cloud-platform"],
        "lifetime": "3600s"
    }

    try:
        iam_resp = requests.post(iam_url, headers=iam_headers, json=iam_payload, timeout=15)
    except Exception as e:
        logger.error(f"[Step 3 FAILED] Could not call IAM Credentials API: {e}")
        sys.exit(1)

    if iam_resp.status_code != 200:
        logger.error(f"[Step 3 FAILED] IAM Credentials API returned HTTP {iam_resp.status_code}: {iam_resp.text}")
        logger.error(f"Troubleshooting: Ensure roles/iam.workloadIdentityUser is bound on {target_sa} for principal://.../subject/client-01.")
        sys.exit(1)

    iam_data = iam_resp.json()
    impersonated_token = iam_data.get("accessToken")
    logger.info("[Step 3 SUCCESS] Obtained GCP OAuth 2.0 Access Token for Target Service Account!")
    logger.info(f"  -> Impersonated Token Prefix: {impersonated_token[:15]}... (Expire Time: {iam_data.get('expireTime')})")

    # ==========================================================================
    # Step 4: Access Cloud Storage (Verify Authorization)
    # ==========================================================================
    gcs_url = f"https://storage.googleapis.com/storage/v1/b/{bucket_name}/o"
    logger.info(f"[Step 4/4] Verifying authorization by listing objects in GCS bucket: gs://{bucket_name}...")

    gcs_headers = {
        "Authorization": f"Bearer {impersonated_token}",
        "Accept": "application/json"
    }

    try:
        gcs_resp = requests.get(gcs_url, headers=gcs_headers, timeout=15)
    except Exception as e:
        logger.error(f"[Step 4 FAILED] Could not call GCS API: {e}")
        sys.exit(1)

    if gcs_resp.status_code != 200:
        logger.error(f"[Step 4 FAILED] GCS API returned HTTP {gcs_resp.status_code}: {gcs_resp.text}")
        logger.error(f"Troubleshooting: Ensure roles/storage.objectViewer is granted to {target_sa} on bucket gs://{bucket_name}.")
        sys.exit(1)

    gcs_data = gcs_resp.json()
    items = gcs_data.get("items", [])
    logger.info("[Step 4 SUCCESS] Successfully listed objects in Cloud Storage bucket!")
    logger.info("=" * 78)
    logger.info(f"  Bucket Name: gs://{bucket_name}")
    logger.info(f"  Total Objects Found: {len(items)}")
    for idx, item in enumerate(items, 1):
        logger.info(f"    [{idx}] {item.get('name')} (Size: {item.get('size')} bytes, Updated: {item.get('updated')})")
    logger.info("=" * 78)
    logger.info("PROOF-OF-CONCEPT DEMO EXECUTED WITH 100% SUCCESS!")
    logger.info("=" * 78)


if __name__ == "__main__":
    main()
